### ISSUE TITLE
Exclude files via script/deploy only dist directory

### ISSUE THREAD

**Issue by sc00** [SamKirkland/ftp-deploy#15]
Hi,
is it possible to exclude files like package.json from deployment via script + CLI as well? Or is it perhaps possible to only sync a specific directory like "dist"?
Thanks and cheers

**Comment by SamKirkland** [comment]
Yes! If you want to output all the options with examples simply run the `ftp-deploy` command without options.

Exclude expects an array of patterns to exclude. Because its an array specify the exclude option more than once.

Example (untested code):
```script
ftp-deploy --server ftp.samkirkland.com --username test@samkirkland.com --password \"CrazyUniquePassword&%123\" --exclude dist/** --exclude **/.git* --exclude **/.git*/** --exclude **/node_modules/** --exclude **/package.json
```
