### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by a-tonchev** [SamKirkland/ftp-deploy#33]
I get memory leak warning when I have more than 10 usages of ftp-deploy

![image](https://github.com/SamKirkland/ftp-deploy/assets/54528540/81c4476a-eb5b-474c-bf01-dfb4bc5fd9a3)

It looks like the problem comes somewhere from bluebird, that is used by promise-ftp

Any idea how to fix that?

**Comment by SamKirkland** [comment]
Fixed with basic-ftp upgrade, available in latest release!
https://github.com/SamKirkland/ftp-deploy/releases/tag/v1.2.4
