### ISSUE TITLE
node 16 is not support  anymore from from github need to update to  version 20

### ISSUE THREAD

**Issue by moqasalem** [SamKirkland/ftp-deploy#38]
Hello Everyone , since two day i am trying to upload my laravel project to live serve using FTP  
but I got this error >
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, SamKirkland/FTP-Deploy-Action@v4.3.4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

my ymal file is:
on:
  #  push:
  #    branches:
  #      - main
 pull_request:
   branches:
     - main
name: 🚀 Deploy website on pull_request
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.domain.com
          username: user@domain.com
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/
          exclude: public_html/.env

**Comment by SamKirkland** [comment]
Upgraded to node 20 in latest release
https://github.com/SamKirkland/ftp-deploy/releases/tag/v1.2.4
