### ISSUE TITLE
Deploy only Modfied files (part of the PR)

### ISSUE THREAD

**Issue by francois-viglob** [SamKirkland/ftp-deploy#40]
Is there a way to deploy only modified file that are part of the PR (of my PR contains 5 files, I want only these 4 files to be uploaded to the server).

Thanks for your help!
____
This yaml download everything, even if the pr contains only 4 files.

-->

name: 🚀 Deployer sur site FTP 'francois' 

on:
  pull_request:
    branches:
      - FTP_dev

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Récupère le code
      uses: actions/checkout@v4

    - name: 📂 Synchronise les fichiers(check deploy4)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

**Comment by SamKirkland** [comment]
Yes! See the `--exclude` option in the readme https://github.com/SamKirkland/ftp-deploy
